---
- name: install apt packages
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - git
    - libjpeg-dev
    - libpq-dev
    - memcached
    - nginx
    - python
    - python3
    - python-dev
    - python-pip
    - python3-pip
    - python-psycopg2
    - python3-psycopg2
    - python-setuptools
    - python-virtualenv
    - supervisor

- include: django.yml

- include: nginx.yml